version: '3.0'
services:
  dev-db:
    image: postgres
    restart: unless-stopped
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: RESTdbTest1
    volumes:
      - .docker-data/postgres:/var/lib/postgresql/data
